version: "2.3"
services:
  pix2face: &pix2face
    build:
      context: .
      dockerfile: Dockerfile
    image: pix2face:pix2face_main
    environment:
      - DOCKER_USERNAME=pix2face_user
      - DISPLAY
      - MXNET_CUDNN_AUTOTUNE_DEFAULT=0
      - MXNET_ENABLE_GPU_P2P=0
      - PYTHONPATH=/pix2face/install/python
    volumes:
      - type: volume
        source: home
        target: /home/pix2face_user
      - type: bind
        source: ..
        target: /pix2face
      - type: volume
        source: pix2face_build
        target: /pix2face/build
      - type: volume
        source: pix2face_venv
        target: /pix2face/venv
      - type: volume
        source: pix2face_install
        target: /pix2face/install
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    runtime: nvidia
volumes:
  home:
  pix2face_build:
  pix2face_install:
  pix2face_venv:
