version: "2.4"
services:
  pix2face: &pix2face
    build:
      context: .
      args:
        - user_id=${USER_ID-1000}
    image: pix2face
    volumes:
      - type: bind
        source: ..
        target: /pix2face_super
      - type: volume
        source: pix2face_build-cpu
        target: /pix2face_build
      - type: volume
        source: pix2face_install-cpu
        target: /pix2face_install
    cap_add:
      - SYS_PTRACE  # for gdb
  pix2face-gpu:
    <<: *pix2face
    runtime: nvidia
    build:
      context: .
      args:
        - from=nvidia/cudagl:9.1-devel-centos7
        - user_id=${USER_ID-1000}
    volumes:
      - type: bind
        source: ..
        target: /pix2face_super
      - type: volume
        source: pix2face_build-gpu
        target: /pix2face_build
      - type: volume
        source: pix2face_install-gpu
        target: /pix2face_install
volumes:
  pix2face_build-cpu:
  pix2face_install-cpu:
  pix2face_build-gpu:
  pix2face_install-gpu:
